module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'whiteDark': '#D9D9D9',
      'offWhite': '#EBEAE9',
      'yellowLight': '#FFF4C7',
      'mainBlue': '#3A46A9',
      'lightBlueDark': '#2e728f',
      'lightBlue': '#4e57a6',
      'disableBlue': '#7d83b2',
      'midnight': '#121063',
      'text': '#282828',
      'metal': '#565584',
      'graph': '#656565',
      'tahiti': '#3ab7bf',
      'complete': '#E2EFDA',
      'pending': '#FEDC81',
      'orangeDark': '#ad7430',
      'orange': '#e8891a',
      'cancel': '#F8696B',
      'silver': '#ecebff',
      'grey': '#646464',
      'lightgrey': '#f5f5f5',
      'errorBg': '#ffeeee',
      'red': '#E03C08',
      'red2': '#3A46A9',
      'green': '#20A100',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
    },
  },
  plugins: [],
}