module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'whiteDark': '#D9D9D9',
      'offWhite': '#EBEAE9',
      'yellowLight': '#FFF4C7',
      'mainBlue': '#3A46A9',
      'midnight': '#121063',
      'text': '#1c1c1c',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'grey': '#646464',
      'lightgrey': '#f8f8f8',
      'errorBg': '#ffeeee',
      'red': '#E03C08',
      'green': '#20A100',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
    },
  },
  plugins: [],
}